# Credit for fingerprint action https://github.com/expo/expo
# https://github.com/expo/expo/blob/main/.github/workflows/pr-labeler.yml
---
name: PR Tests

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  actions: write
  contents: read

jobs:
  webpack-analyzer:
    runs-on: ubuntu-22.04
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository && github.event_name == 'pull_request'}}
    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ğŸ”§ Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Ensure tracking relevant branches and checkout base
        env:
          HEAD_REF: ${{ github.head_ref }}
          BASE_REF: ${{ github.base_ref }}
        run: |
          git checkout $HEAD_REF
          git checkout $BASE_REF

      - name: Get the base commit
        id: base-commit
        env:
          BASE_REF: ${{ github.base_ref }}
        run: echo base-commit=$(git log -n 1 $BASE_REF --pretty=format:'%H') >> "$GITHUB_OUTPUT"

      - name: Merge PR commit
        env:
          HEAD_REF: ${{ github.head_ref }}
        run: |
          # Have to set a git config for the merge to work
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git merge --no-edit $HEAD_REF
          yarn install
          yarn intl:build

      - name: ğŸ”¦ Generate stats file for PR
        run: |
          yarn generate-webpack-stats-file
          mv stats.json ../stats-new.json

      - name: â¬‡ï¸ Get base stats from cache
        id: get-base-stats
        uses: actions/cache@v4
        with:
          path: stats-base.json
          key: stats-base-${{ steps.base-commit.outputs.base-commit }}

      - name: Restore to base commit
        if: ${{ !steps.get-base-stats.outputs.cache-hit }}
        run: |
          git reset HEAD~
          git restore .

      - name: ğŸ”¦ Generate stats file from base commit
        if: ${{ !steps.get-base-stats.outputs.cache-hit }}
        run: |
          yarn install
          yarn intl:build
          yarn generate-webpack-stats-file
          mv stats.json stats-base.json

      - name: ï¼… Get diff
        id: get-diff
        uses: NejcZdovc/bundle-size-diff@v1
        with:
          base_path: "stats-base.json"
          pr_path: "../stats-new.json"
          excluded_assets: "(.+).chunk.js|(.+).js.map|(.+).json|(.+).png|(.+).svg|(.+).webp|(.+).jpg|(.+).ico"

      - name: ğŸ’¬ Drop a comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: bundle-diff
          message: |
            | Old size | New size | Diff                  |
            |----------|----------|-----------------------|
            | ${{ steps.get-diff.outputs.base_file_string }} | ${{ steps.get-diff.outputs.pr_file_string }} | ${{ steps.get-diff.outputs.diff_file_string }} (${{ steps.get-diff.outputs.percent }}%) |
            ---

  fingerprint-native:
    runs-on: ubuntu-22.04
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository && github.event_name == 'pull_request'}}
    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: â¬‡ï¸ Fetch commits from base branch
        run: git fetch origin main:main --depth 100
        if: github.event_name == 'pull_request'

      - name: ğŸ”§ Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: ğŸ“· Check fingerprint and install dependencies
        id: fingerprint
        uses: bluesky-social/github-actions/fingerprint-native@main
        with:
          profile: pull-request

      - name: ğŸ’¬ Drop a comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ steps.fingerprint.outputs.includes-changes }}
        with:
          header: fingerprint-diff
          message: |
            The Pull Request introduced fingerprint changes against the base commit:
            <details><summary>Fingerprint diff</summary>

            ```json
            ${{ steps.fingerprint.outputs.diff }}
            ```

            </details>

            ---
            *Generated by [PR labeler](https://github.com/expo/expo/actions/workflows/pr-labeler.yml) ğŸ¤–*

      - name: ğŸ’¬ Delete comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ !steps.fingerprint.outputs.includes-changes }}
        with:
          header: fingerprint-diff
          delete: true
